# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SWaT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 708)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(70, 30, 611, 611))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalWidget = QtWidgets.QWidget(self.horizontalWidget)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalWidget1 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabInit1 = QtWidgets.QLabel(self.horizontalWidget1)
        self.LabInit1.setMaximumSize(QtCore.QSize(60, 30))
        self.LabInit1.setObjectName("LabInit1")
        self.horizontalLayout.addWidget(self.LabInit1)
        self.EditInit1 = QtWidgets.QTextEdit(self.horizontalWidget1)
        self.EditInit1.setMaximumSize(QtCore.QSize(120, 30))
        self.EditInit1.setObjectName("EditInit1")
        self.horizontalLayout.addWidget(self.EditInit1)
        self.verticalLayout.addWidget(self.horizontalWidget1)
        self.horizontalWidget2 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget2.setObjectName("horizontalWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalWidget2)
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.LabInit2 = QtWidgets.QLabel(self.horizontalWidget2)
        self.LabInit2.setMaximumSize(QtCore.QSize(60, 30))
        self.LabInit2.setObjectName("LabInit2")
        self.horizontalLayout_6.addWidget(self.LabInit2)
        self.EditInit2 = QtWidgets.QTextEdit(self.horizontalWidget2)
        self.EditInit2.setMaximumSize(QtCore.QSize(120, 30))
        self.EditInit2.setObjectName("EditInit2")
        self.horizontalLayout_6.addWidget(self.EditInit2)
        self.verticalLayout.addWidget(self.horizontalWidget2)
        self.horizontalWidget3 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget3.setObjectName("horizontalWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalWidget3)
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.LabInit3 = QtWidgets.QLabel(self.horizontalWidget3)
        self.LabInit3.setMaximumSize(QtCore.QSize(60, 30))
        self.LabInit3.setObjectName("LabInit3")
        self.horizontalLayout_5.addWidget(self.LabInit3)
        self.EditInit3 = QtWidgets.QTextEdit(self.horizontalWidget3)
        self.EditInit3.setMaximumSize(QtCore.QSize(120, 30))
        self.EditInit3.setObjectName("EditInit3")
        self.horizontalLayout_5.addWidget(self.EditInit3)
        self.verticalLayout.addWidget(self.horizontalWidget3)
        self.horizontalWidget4 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget4.setObjectName("horizontalWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget4)
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LabInit4 = QtWidgets.QLabel(self.horizontalWidget4)
        self.LabInit4.setMaximumSize(QtCore.QSize(60, 30))
        self.LabInit4.setObjectName("LabInit4")
        self.horizontalLayout_4.addWidget(self.LabInit4)
        self.EditInit4 = QtWidgets.QTextEdit(self.horizontalWidget4)
        self.EditInit4.setMaximumSize(QtCore.QSize(120, 30))
        self.EditInit4.setObjectName("EditInit4")
        self.horizontalLayout_4.addWidget(self.EditInit4)
        self.verticalLayout.addWidget(self.horizontalWidget4)
        self.horizontalWidget5 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget5.setObjectName("horizontalWidget5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget5)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LabInit5 = QtWidgets.QLabel(self.horizontalWidget5)
        self.LabInit5.setMaximumSize(QtCore.QSize(60, 30))
        self.LabInit5.setObjectName("LabInit5")
        self.horizontalLayout_3.addWidget(self.LabInit5)
        self.EditInit5 = QtWidgets.QTextEdit(self.horizontalWidget5)
        self.EditInit5.setMaximumSize(QtCore.QSize(120, 30))
        self.EditInit5.setObjectName("EditInit5")
        self.horizontalLayout_3.addWidget(self.EditInit5)
        self.verticalLayout.addWidget(self.horizontalWidget5)
        self.horizontalWidget6 = QtWidgets.QWidget(self.verticalWidget)
        self.horizontalWidget6.setMinimumSize(QtCore.QSize(10, 10))
        self.horizontalWidget6.setObjectName("horizontalWidget6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StartBtn = QtWidgets.QPushButton(self.horizontalWidget6)
        self.StartBtn.setMinimumSize(QtCore.QSize(60, 40))
        self.StartBtn.setMaximumSize(QtCore.QSize(80, 60))
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout_2.addWidget(self.StartBtn)
        self.StopBtn = QtWidgets.QPushButton(self.horizontalWidget6)
        self.StopBtn.setMaximumSize(QtCore.QSize(80, 60))
        self.StopBtn.setObjectName("StopBtn")
        self.horizontalLayout_2.addWidget(self.StopBtn)
        self.StepBtn = QtWidgets.QPushButton(self.horizontalWidget6)
        self.StepBtn.setMaximumSize(QtCore.QSize(80, 60))
        self.StepBtn.setObjectName("StepBtn")
        self.horizontalLayout_2.addWidget(self.StepBtn)
        self.verticalLayout.addWidget(self.horizontalWidget6)
        self.horizontalLayout_7.addWidget(self.verticalWidget)
        self.verticalWidget1 = QtWidgets.QWidget(self.horizontalWidget)
        self.verticalWidget1.setMinimumSize(QtCore.QSize(300, 20))
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LabOutput1 = QtWidgets.QLabel(self.verticalWidget1)
        self.LabOutput1.setObjectName("LabOutput1")
        self.verticalLayout_2.addWidget(self.LabOutput1)
        self.LabOutput2 = QtWidgets.QLabel(self.verticalWidget1)
        self.LabOutput2.setObjectName("LabOutput2")
        self.verticalLayout_2.addWidget(self.LabOutput2)
        self.LabOutput3 = QtWidgets.QLabel(self.verticalWidget1)
        self.LabOutput3.setObjectName("LabOutput3")
        self.verticalLayout_2.addWidget(self.LabOutput3)
        self.horizontalLayout_7.addWidget(self.verticalWidget1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LabInit1.setText(_translate("MainWindow", "Init 1"))
        self.EditInit1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">505</p></body></html>"))
        self.LabInit2.setText(_translate("MainWindow", "Init 2"))
        self.EditInit2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">890</p></body></html>"))
        self.LabInit3.setText(_translate("MainWindow", "Init 3"))
        self.EditInit3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">900</p></body></html>"))
        self.LabInit4.setText(_translate("MainWindow", "Init 4"))
        self.EditInit4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>"))
        self.LabInit5.setText(_translate("MainWindow", "Init 5"))
        self.EditInit5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">200</p></body></html>"))
        self.StartBtn.setText(_translate("MainWindow", "Run"))
        self.StopBtn.setText(_translate("MainWindow", "Stop"))
        self.StepBtn.setText(_translate("MainWindow", "Step"))
        self.LabOutput1.setText(_translate("MainWindow", "Output1"))
        self.LabOutput2.setText(_translate("MainWindow", "Output2"))
        self.LabOutput3.setText(_translate("MainWindow", "Output3"))
